FROM node:22-alpine3.20 as npm-build

COPY . /tmp
WORKDIR /tmp
RUN npm install && npm install sharp
RUN npm run build .

FROM alpine:3.20

RUN apk add --no-cache \
    bash curl less ca-certificates git \
    tzdata zip gettext sed \
    nginx curl supervisor certbot-nginx

COPY container/default.conf /etc/nginx/http.d/default.conf
COPY container/nginx.conf /etc/nginx/nginx.conf
COPY container/supervisord.conf /etc/supervisord.conf

COPY container/init_cert.sh /usr/local/bin/init_cert.sh
COPY container/init_react_envs.sh /usr/local/bin/init_react_envs.sh
COPY container/start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/init_cert.sh /usr/local/init_react_envs.sh /usr/local/start.sh

COPY --from=npm-build /tmp/out/ /usr/share/nginx/html/

WORKDIR /usr/share/nginx/html
STOPSIGNAL SIGINT
EXPOSE 80
EXPOSE 443
ENTRYPOINT ["/usr/bin/supervisord","-c","/etc/supervisord.conf"]